# Generated by Django 5.2.5 on 2025-09-03 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this project belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='categories.category'),
        ),
    ]
